### ISSUE TITLE
Dependency issues - `{jtools}` & `{weights}`

### ISSUE THREAD

**Issue by zackarno** [mhkhan27/illuminate#1]
Hi @mhkhan27 , finally getting around to trying out `{illuminate}` - looks cool. I think you should add `{jtools}` and `{weights}` packages as dependencies. 

I was using it in the IRQ RS work and got a message saying NAMESPACE error regarding `{jtools}` and later `{weights}` - it took me a bit to figure out the dependency issue was coming from `{illuminate}` so you might as well add them as dependencies?

**Comment by mhkhan27** [comment]
Hey Zack, Thanks for flagging this. I have added them as dependencies in the development branch. Will merge soon! Thanks
